### ISSUE TITLE
 Root project in Git is incorrect hierarchy.

### ISSUE THREAD

**Issue by thuypt** [sagarekbote/surveys#1]
The root of the repository should be 
<img width="300" alt="screen shot 2561-04-19 at 10 21 56" src="https://user-images.githubusercontent.com/6264092/38969649-85bbb9bc-43bb-11e8-9839-3b43159c5e0e.png">

instead of start with directory `/nimbl3`

**Comment by sagarekbote** [comment]
removed the unwanted directory
