### ISSUE TITLE
Request configuration for build flavor. 

### ISSUE THREAD

**Issue by thuypt** [sagarekbote/surveys#5]

**Comment by sagarekbote** [comment]
so the ask is to create some random build flavors like say red and blue or customer and admin ?

**Comment by thuypt** [comment]
Yes, you can create different versions of the app from a single project as your example `customer`, `admin` ( `Build Types` or `Product Flavors`).

**Comment by sagarekbote** [comment]
PR https://github.com/sagarekbote/surveys/pull/10
