### ISSUE TITLE
Code format/convention is inconsistent

### ISSUE THREAD

**Issue by thuypt** [sagarekbote/surveys#7]
- Some of `private` variable has `m pre-fix`, some not
- Code format has many styles
For example:
<img width="605" alt="screen shot 2561-04-19 at 10 37 21" src="https://user-images.githubusercontent.com/6264092/38970106-cd31a174-43bd-11e8-8ea4-88fc661ef5e9.png">
<img width="363" alt="screen shot 2561-04-19 at 10 37 29" src="https://user-images.githubusercontent.com/6264092/38970113-d5337d70-43bd-11e8-99ae-ae483af911a5.png">

**Comment by sagarekbote** [comment]
the private variables which didnt had 'm' prefix were were auto generated using json2pojo plugin in AS. Added m prefix to all variables and formatted the code

**Comment by thuypt** [comment]
Please attach the commit reference that fixed regarding issues, it can help us understand clearly how you fixed it.

**Comment by sagarekbote** [comment]
https://github.com/sagarekbote/surveys/commit/1324e33187b2134cc902c8aec01515eeb7e0e247
